# docker-compose.dev.yml
# Service Geliştirme ortamı

networks:
  sentiric-net:
    name: "${NETWORK_NAME:-sentiric-net}"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}

volumes:
  # [capability-tts]: Konuşma Sentezleme Yetenekleri (TTS Capabilities)
  # --------------------------------------------------            
  tts-coqui-model-cache:

services:
  tts-coqui-service:
    build:
      context: ../sentiric-tts-coqui-service
      args:
        PYTHON_VERSION: 3.11
        BASE_IMAGE_TAG: "3.11-slim-bullseye"
        PYTORCH_EXTRA_INDEX_URL: "https://download.pytorch.org/whl/cpu"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    env_file: ["${ENV_FILE_PATH}"]
    volumes: 
      - "${CONFIG_REPO_PATH}:/sentiric-config:ro"
      - "${CERTIFICATES_REPO_PATH}:/sentiric-certificates:ro"
      - "${ASSETS_REPO_PATH}:/sentiric-assets:ro"
      # YENİ: Model cache'ini volume'a bağla
      - tts-coqui-model-cache:/home/appuser/.local/share/tts
    ports: 
      - "14030:${TTS_COQUI_SERVICE_HTTP_PORT:-14030}"
      - "14031:${TTS_COQUI_SERVICE_GRPC_PORT:-14031}"
      - "14032:${TTS_COQUI_SERVICE_METRICS_PORT:-14032}"          
    networks:
      sentiric-net:
        ipv4_address: ${TTS_COQUI_SERVICE_IPV4_ADDRESS}       
    restart: always